services:
  joern:
    image: ghcr.io/joernio/joern:nightly
    command: [ "sh", "-c", "joern --server --server-host 0.0.0.0 --server-port 8080" ]
    ports:
      - "8080:8080"
    volumes:
      - /tmp/graphide_exchange:/data/exchange
